/**
 * BrandSparkX — Rich Demo/Mock Data
 * Provides realistic seed data for the demo mode (no backend required).
 */

const now = new Date();
const daysFromNow = (n) => { const d = new Date(now); d.setDate(d.getDate() + n); return d.toISOString().split('T')[0]; };
const daysAgo = (n) => daysFromNow(-n);

// ── Users ────────────────────────────────────────────────────
export const MOCK_USERS = [
  { id: 'usr-001', name: 'Admin User', email: 'admin@brandsparkx.com', role: 'admin', is_active: true, working_on: 'System Administration & Security', employee_status: 'Active' },
  { id: 'usr-002', name: 'Priya Sharma', email: 'manager@brandsparkx.com', role: 'manager', is_active: true, working_on: 'SLA Escalations & Contract Signoff', employee_status: 'Active' },
  { id: 'usr-003', name: 'Ravi Kumar', email: 'staff@brandsparkx.com', role: 'staff', is_active: true, working_on: 'Reviewing SLA breach incidents & alerts', employee_status: 'Active' },
];

// ── Customers ────────────────────────────────────────────────
export const MOCK_CUSTOMERS = [
  { id: 'cus-001', customer_number: 'CUS-0001', name: 'Arjun Mehta', company_name: 'TechNova Solutions Pvt Ltd', email: 'arjun@technova.com', phone: '+91-9876543210', address: 'Whitefield, Bangalore, Karnataka', industry: 'Information Technology', country: 'India', status: 'active', contract_count: '6', created_at: daysAgo(180) },
  { id: 'cus-002', customer_number: 'CUS-0002', name: 'Sneha Patel', company_name: 'FinEdge Capital Ltd', email: 'sneha@finedge.in', phone: '+91-9765432109', address: 'BKC, Mumbai, Maharashtra', industry: 'Banking & Finance', country: 'India', status: 'active', contract_count: '4', created_at: daysAgo(150) },
  { id: 'cus-003', customer_number: 'CUS-0003', name: 'Rajesh Kumar', company_name: 'HealthFirst Hospitals', email: 'rajesh@healthfirst.com', phone: '+91-9654321098', address: 'T Nagar, Chennai, Tamil Nadu', industry: 'Healthcare', country: 'India', status: 'active', contract_count: '3', created_at: daysAgo(120) },
  { id: 'cus-004', customer_number: 'CUS-0004', name: 'Meera Iyer', company_name: 'AutoPrime Manufacturing', email: 'meera@autoprime.co', phone: '+91-9543210987', address: 'Pimpri-Chinchwad, Pune, Maharashtra', industry: 'Manufacturing', country: 'India', status: 'active', contract_count: '5', created_at: daysAgo(200) },
  { id: 'cus-005', customer_number: 'CUS-0005', name: 'Vikram Singh', company_name: 'RetailMax India', email: 'vikram@retailmax.in', phone: '+91-9432109876', address: 'Connaught Place, New Delhi', industry: 'Retail & E-Commerce', country: 'India', status: 'active', contract_count: '7', created_at: daysAgo(90) },
  { id: 'cus-006', customer_number: 'CUS-0006', name: 'Divya Nair', company_name: 'EduLeap Technologies', email: 'divya@eduleap.edu', phone: '+91-9321098765', address: 'Hitech City, Hyderabad, Telangana', industry: 'Education', country: 'India', status: 'active', contract_count: '2', created_at: daysAgo(60) },
  { id: 'cus-007', customer_number: 'CUS-0007', name: 'Suresh Gupta', company_name: 'PharmaGen Labs', email: 'suresh@pharmagen.com', phone: '+91-9210987654', address: 'Andheri East, Mumbai', industry: 'Pharmaceuticals', country: 'India', status: 'active', contract_count: '3', created_at: daysAgo(300) },
  { id: 'cus-008', customer_number: 'CUS-0008', name: 'Anita Desai', company_name: 'LogiTrack Express', email: 'anita@logitrack.com', phone: '+91-9109876543', address: 'Sector 62, Noida, UP', industry: 'Logistics & Supply Chain', country: 'India', status: 'active', contract_count: '4', created_at: daysAgo(240) },
  { id: 'cus-009', customer_number: 'CUS-0009', name: 'Karthik Reddy', company_name: 'PowerGen Energy', email: 'karthik@powergen.co', phone: '+91-9098765432', address: 'Madhapur, Hyderabad', industry: 'Energy', country: 'India', status: 'inactive', contract_count: '1', created_at: daysAgo(400) },
  { id: 'cus-010', customer_number: 'CUS-0010', name: 'Preethi Rao', company_name: 'MediaStar Productions', email: 'preethi@mediastar.tv', phone: '+91-8987654321', address: 'Film Nagar, Hyderabad', industry: 'Media & Entertainment', country: 'India', status: 'active', contract_count: '2', created_at: daysAgo(75) },
  { id: 'cus-011', customer_number: 'CUS-0011', name: 'Amit Joshi', company_name: 'BuildRight Realty', email: 'amit@buildright.co', phone: '+91-8876543210', address: 'Koregaon Park, Pune', industry: 'Real Estate', country: 'India', status: 'prospect', contract_count: '0', created_at: daysAgo(30) },
  { id: 'cus-012', customer_number: 'CUS-0012', name: 'Pooja Sharma', company_name: 'InsureWell Corporation', email: 'pooja@insurewell.in', phone: '+91-8765432109', address: 'Nariman Point, Mumbai', industry: 'Insurance', country: 'India', status: 'active', contract_count: '3', created_at: daysAgo(160) },
  { id: 'cus-013', customer_number: 'CUS-0013', name: 'Naresh Babu', company_name: 'SpeedNet Telecom', email: 'naresh@speednet.in', phone: '+91-8654321098', address: 'Electronic City, Bangalore', industry: 'Telecom', country: 'India', status: 'active', contract_count: '2', created_at: daysAgo(210) },
  { id: 'cus-014', customer_number: 'CUS-0014', name: 'Lalitha Krishnan', company_name: 'FreshMart FMCG', email: 'lalitha@freshmart.com', phone: '+91-8543210987', address: 'Anna Salai, Chennai', industry: 'FMCG', country: 'India', status: 'active', contract_count: '3', created_at: daysAgo(130) },
  { id: 'cus-015', customer_number: 'CUS-0015', name: 'Rohit Verma', company_name: 'AutoDrive Motors', email: 'rohit@autodrive.in', phone: '+91-8432109876', address: 'Manesar, Gurugram, Haryana', industry: 'Automotive', country: 'India', status: 'active', contract_count: '4', created_at: daysAgo(185) },
  { id: 'cus-016', customer_number: 'CUS-0016', name: 'Sujatha Pillai', company_name: 'CloudSoft Systems', email: 'sujatha@cloudsoft.io', phone: '+91-8321098765', address: 'Infopark, Kochi, Kerala', industry: 'Information Technology', country: 'India', status: 'active', contract_count: '5', created_at: daysAgo(95) },
  { id: 'cus-017', customer_number: 'CUS-0017', name: 'Deepak Malhotra', company_name: 'Axis Steel Works', email: 'deepak@axissteel.com', phone: '+91-8210987654', address: 'Industrial Area, Ludhiana, Punjab', industry: 'Manufacturing', country: 'India', status: 'active', contract_count: '2', created_at: daysAgo(320) },
  { id: 'cus-018', customer_number: 'CUS-0018', name: 'Kavya Menon', company_name: 'GreenPath Agriculture', email: 'kavya@greenpath.in', phone: '+91-8109876543', address: 'Coimbatore, Tamil Nadu', industry: 'FMCG', country: 'India', status: 'prospect', contract_count: '0', created_at: daysAgo(20) },
  { id: 'cus-019', customer_number: 'CUS-0019', name: 'Arun Srivastava', company_name: 'DataVault Analytics', email: 'arun@datavault.ai', phone: '+91-8098765432', address: 'Cyber City, Gurugram', industry: 'Information Technology', country: 'India', status: 'active', contract_count: '3', created_at: daysAgo(110) },
  { id: 'cus-020', customer_number: 'CUS-0020', name: 'Sunita Kapoor', company_name: 'AirFreight Global', email: 'sunita@airfreight.com', phone: '+91-7987654321', address: 'Sahar, Mumbai', industry: 'Logistics & Supply Chain', country: 'India', status: 'active', contract_count: '2', created_at: daysAgo(50) },
];

// ── Contracts ────────────────────────────────────────────────
export const MOCK_CONTRACTS = [
  // Expiring very soon (critical alerts)
  { id: 'con-001', contract_number: 'CON-2024-0001', customer_id: 'cus-001', title: 'Annual IT Infrastructure Support Agreement', contract_type: 'Service Agreement', value: 2500000, start_date: daysAgo(335), end_date: daysFromNow(30), renewal_date: daysFromNow(5), deliverable_timeline: '30 days', sla_commitment: '4hr response; 24hr resolution', priority: 'critical', status: 'active', description: 'Comprehensive IT support covering all infrastructure components.', customer_name: 'Arjun Mehta', company_name: 'TechNova Solutions Pvt Ltd', sla_count: 3, open_incidents: 1, created_by_name: 'Admin User', created_at: daysAgo(335), updated_at: daysAgo(10) },
  { id: 'con-002', contract_number: 'CON-2024-0002', customer_id: 'cus-002', title: 'Core Banking System Maintenance Contract', contract_type: 'Maintenance Contract', value: 4800000, start_date: daysAgo(300), end_date: daysFromNow(60), renewal_date: daysFromNow(15), deliverable_timeline: '90 days', sla_commitment: '2hr response; 8hr resolution', priority: 'critical', status: 'active', description: 'Full maintenance of CBS including 24x7 monitoring.', customer_name: 'Sneha Patel', company_name: 'FinEdge Capital Ltd', sla_count: 4, open_incidents: 2, created_by_name: 'Admin User', created_at: daysAgo(300), updated_at: daysAgo(5) },
  { id: 'con-003', contract_number: 'CON-2024-0003', customer_id: 'cus-003', title: 'Hospital Management Software SLA', contract_type: 'SLA Contract', value: 1800000, start_date: daysAgo(280), end_date: daysFromNow(25), renewal_date: daysFromNow(3), deliverable_timeline: '60 days', sla_commitment: '1hr response; 4hr resolution', priority: 'high', status: 'active', description: 'SLA for HMS covering patient management and billing.', customer_name: 'Rajesh Kumar', company_name: 'HealthFirst Hospitals', sla_count: 2, open_incidents: 1, created_by_name: 'Priya Sharma', created_at: daysAgo(280), updated_at: daysAgo(3) },

  // Expiring in ~30 days (warning alerts)
  { id: 'con-004', contract_number: 'CON-2024-0004', customer_id: 'cus-004', title: 'Manufacturing ERP Consulting Agreement', contract_type: 'Consulting Agreement', value: 3200000, start_date: daysAgo(335), end_date: daysFromNow(90), renewal_date: daysFromNow(28), deliverable_timeline: '120 days', sla_commitment: '8hr response; 48hr resolution', priority: 'high', status: 'active', description: 'SAP implementation and post-go-live support.', customer_name: 'Meera Iyer', company_name: 'AutoPrime Manufacturing', sla_count: 2, open_incidents: 0, created_by_name: 'Admin User', created_at: daysAgo(335), updated_at: daysAgo(20) },
  { id: 'con-005', contract_number: 'CON-2024-0005', customer_id: 'cus-005', title: 'E-Commerce Platform License Agreement', contract_type: 'Licensing Agreement', value: 960000, start_date: daysAgo(300), end_date: daysFromNow(95), renewal_date: daysFromNow(22), deliverable_timeline: '30 days', sla_commitment: '4hr response; 24hr resolution', priority: 'medium', status: 'active', description: 'Annual platform licensing with feature updates.', customer_name: 'Vikram Singh', company_name: 'RetailMax India', sla_count: 2, open_incidents: 1, created_by_name: 'Priya Sharma', created_at: daysAgo(300), updated_at: daysAgo(15) },

  // Active contracts (healthy)
  { id: 'con-006', contract_number: 'CON-2024-0006', customer_id: 'cus-006', title: 'LMS Development & SLA Support', contract_type: 'SLA Contract', value: 750000, start_date: daysAgo(60), end_date: daysFromNow(305), renewal_date: daysFromNow(270), deliverable_timeline: '90 days', sla_commitment: '8hr response; 48hr resolution', priority: 'medium', status: 'active', description: 'Learning Management System with student portal.', customer_name: 'Divya Nair', company_name: 'EduLeap Technologies', sla_count: 1, open_incidents: 0, created_by_name: 'Admin User', created_at: daysAgo(60), updated_at: daysAgo(2) },
  { id: 'con-007', contract_number: 'CON-2024-0007', customer_id: 'cus-007', title: 'Pharma R&D Data Management Partnership', contract_type: 'Partnership Agreement', value: 5600000, start_date: daysAgo(90), end_date: daysFromNow(275), renewal_date: daysFromNow(240), deliverable_timeline: '180 days', sla_commitment: '4hr response; 24hr resolution', priority: 'high', status: 'active', description: 'Clinical trial data management and compliance.', customer_name: 'Suresh Gupta', company_name: 'PharmaGen Labs', sla_count: 3, open_incidents: 0, created_by_name: 'Admin User', created_at: daysAgo(90), updated_at: daysAgo(7) },
  { id: 'con-008', contract_number: 'CON-2024-0008', customer_id: 'cus-008', title: 'Supply Chain Visibility Platform', contract_type: 'Service Agreement', value: 1400000, start_date: daysAgo(120), end_date: daysFromNow(245), renewal_date: daysFromNow(210), deliverable_timeline: '60 days', sla_commitment: '8hr response; 72hr resolution', priority: 'medium', status: 'active', description: 'Real-time tracking and visibility across logistics network.', customer_name: 'Anita Desai', company_name: 'LogiTrack Express', sla_count: 2, open_incidents: 1, created_by_name: 'Priya Sharma', created_at: daysAgo(120), updated_at: daysAgo(14) },
  { id: 'con-009', contract_number: 'CON-2024-0009', customer_id: 'cus-010', title: 'Media Asset Management System', contract_type: 'Licensing Agreement', value: 850000, start_date: daysAgo(45), end_date: daysFromNow(320), renewal_date: daysFromNow(290), deliverable_timeline: '45 days', sla_commitment: '12hr response; 48hr resolution', priority: 'low', status: 'active', description: 'Digital media asset management and streaming support.', customer_name: 'Preethi Rao', company_name: 'MediaStar Productions', sla_count: 1, open_incidents: 0, created_by_name: 'Admin User', created_at: daysAgo(45), updated_at: daysAgo(1) },
  { id: 'con-010', contract_number: 'CON-2024-0010', customer_id: 'cus-012', title: 'InsureTech Platform Maintenance', contract_type: 'Maintenance Contract', value: 2100000, start_date: daysAgo(150), end_date: daysFromNow(215), renewal_date: daysFromNow(180), deliverable_timeline: '60 days', sla_commitment: '4hr response; 24hr resolution', priority: 'high', status: 'active', description: 'Policy management and claims processing system maintenance.', customer_name: 'Pooja Sharma', company_name: 'InsureWell Corporation', sla_count: 3, open_incidents: 0, created_by_name: 'Admin User', created_at: daysAgo(150), updated_at: daysAgo(5) },

  // Expired contracts
  { id: 'con-011', contract_number: 'CON-2023-0001', customer_id: 'cus-009', title: 'Solar Energy Monitoring System', contract_type: 'Service Agreement', value: 680000, start_date: daysAgo(400), end_date: daysAgo(35), renewal_date: daysAgo(65), deliverable_timeline: '120 days', sla_commitment: '24hr response; 72hr resolution', priority: 'low', status: 'expired', description: 'Solar panel monitoring and maintenance portal.', customer_name: 'Karthik Reddy', company_name: 'PowerGen Energy', sla_count: 1, open_incidents: 0, created_by_name: 'Priya Sharma', created_at: daysAgo(400), updated_at: daysAgo(35) },
  { id: 'con-012', contract_number: 'CON-2023-0002', customer_id: 'cus-013', title: 'Network Infrastructure SLA', contract_type: 'SLA Contract', value: 1200000, start_date: daysAgo(380), end_date: daysAgo(15), renewal_date: daysAgo(45), deliverable_timeline: '30 days', sla_commitment: '2hr response; 8hr resolution', priority: 'high', status: 'expired', description: 'Telecom network uptime and support SLA.', customer_name: 'Naresh Babu', company_name: 'SpeedNet Telecom', sla_count: 2, open_incidents: 1, created_by_name: 'Admin User', created_at: daysAgo(380), updated_at: daysAgo(15) },

  // Draft contracts
  { id: 'con-013', contract_number: 'CON-2024-0011', customer_id: 'cus-016', title: 'Cloud Migration Services Agreement', contract_type: 'Consulting Agreement', value: 3800000, start_date: daysFromNow(15), end_date: daysFromNow(380), renewal_date: daysFromNow(350), deliverable_timeline: '180 days', sla_commitment: '4hr response; 24hr resolution', priority: 'high', status: 'draft', description: 'AWS cloud migration project scope and support.', customer_name: 'Sujatha Pillai', company_name: 'CloudSoft Systems', sla_count: 0, open_incidents: 0, created_by_name: 'Priya Sharma', created_at: daysAgo(5), updated_at: daysAgo(1) },
  { id: 'con-014', contract_number: 'CON-2024-0012', customer_id: 'cus-019', title: 'AI Analytics Platform License', contract_type: 'Licensing Agreement', value: 2200000, start_date: daysFromNow(30), end_date: daysFromNow(395), renewal_date: daysFromNow(360), deliverable_timeline: '90 days', sla_commitment: '8hr response; 48hr resolution', priority: 'medium', status: 'draft', description: 'Business intelligence and predictive analytics platform.', customer_name: 'Arun Srivastava', company_name: 'DataVault Analytics', sla_count: 0, open_incidents: 0, created_by_name: 'Admin User', created_at: daysAgo(3), updated_at: daysAgo(1) },

  // Renewed contracts
  { id: 'con-015', contract_number: 'CON-2022-0001', customer_id: 'cus-014', title: 'FMCG Inventory Management SLA', contract_type: 'SLA Contract', value: 950000, start_date: daysAgo(365), end_date: daysFromNow(180), renewal_date: daysFromNow(150), deliverable_timeline: '30 days', sla_commitment: '8hr response; 48hr resolution', priority: 'medium', status: 'renewed', description: 'Annual renewal of inventory and distribution management.', customer_name: 'Lalitha Krishnan', company_name: 'FreshMart FMCG', sla_count: 2, open_incidents: 0, created_by_name: 'Admin User', created_at: daysAgo(365), updated_at: daysAgo(30) },

  // More active contracts
  { id: 'con-016', contract_number: 'CON-2024-0013', customer_id: 'cus-015', title: 'Automotive Dealer Management System', contract_type: 'Service Agreement', value: 1750000, start_date: daysAgo(180), end_date: daysFromNow(185), renewal_date: daysFromNow(155), deliverable_timeline: '90 days', sla_commitment: '4hr response; 24hr resolution', priority: 'medium', status: 'active', description: 'Complete dealer management system with CRM integration.', customer_name: 'Rohit Verma', company_name: 'AutoDrive Motors', sla_count: 2, open_incidents: 1, created_by_name: 'Admin User', created_at: daysAgo(180), updated_at: daysAgo(10) },
  { id: 'con-017', contract_number: 'CON-2024-0014', customer_id: 'cus-017', title: 'Steel ERP & MES Integration', contract_type: 'Consulting Agreement', value: 4200000, start_date: daysAgo(90), end_date: daysFromNow(275), renewal_date: daysFromNow(245), deliverable_timeline: '150 days', sla_commitment: '8hr response; 48hr resolution', priority: 'high', status: 'active', description: 'SAP ERP and Manufacturing Execution System integration.', customer_name: 'Deepak Malhotra', company_name: 'Axis Steel Works', sla_count: 2, open_incidents: 0, created_by_name: 'Priya Sharma', created_at: daysAgo(90), updated_at: daysAgo(7) },
  { id: 'con-018', contract_number: 'CON-2024-0015', customer_id: 'cus-020', title: 'Air Cargo Tracking Platform SLA', contract_type: 'SLA Contract', value: 1350000, start_date: daysAgo(50), end_date: daysFromNow(315), renewal_date: daysFromNow(285), deliverable_timeline: '60 days', sla_commitment: '2hr response; 12hr resolution', priority: 'high', status: 'active', description: 'Real-time air freight tracking with customs integration.', customer_name: 'Sunita Kapoor', company_name: 'AirFreight Global', sla_count: 2, open_incidents: 0, created_by_name: 'Admin User', created_at: daysAgo(50), updated_at: daysAgo(4) },
  { id: 'con-019', contract_number: 'CON-2024-0016', customer_id: 'cus-005', title: 'Omnichannel Retail Platform Maintenance', contract_type: 'Maintenance Contract', value: 1600000, start_date: daysAgo(200), end_date: daysFromNow(165), renewal_date: daysFromNow(135), deliverable_timeline: '45 days', sla_commitment: '4hr response; 24hr resolution', priority: 'high', status: 'active', description: 'Maintenance for 50+ store POS and web platform.', customer_name: 'Vikram Singh', company_name: 'RetailMax India', sla_count: 3, open_incidents: 2, created_by_name: 'Admin User', created_at: daysAgo(200), updated_at: daysAgo(8) },
  { id: 'con-020', contract_number: 'CON-2024-0017', customer_id: 'cus-001', title: 'DevOps & Cloud Security NDA', contract_type: 'NDA', value: 0, start_date: daysAgo(30), end_date: daysFromNow(335), renewal_date: null, deliverable_timeline: 'N/A', sla_commitment: 'N/A', priority: 'low', status: 'active', description: 'Non-disclosure agreement for cloud architecture consulting.', customer_name: 'Arjun Mehta', company_name: 'TechNova Solutions Pvt Ltd', sla_count: 0, open_incidents: 0, created_by_name: 'Admin User', created_at: daysAgo(30), updated_at: daysAgo(30) },
];

// ── SLA Commitments ──────────────────────────────────────────
export const MOCK_SLAS = [
  { id: 'sla-001', contract_id: 'con-001', sla_name: '24x7 Critical Support', target_response_time: '1 hour', target_resolution_time: '4 hours', status: 'active', compliance_pct: 98.5, last_review_date: daysAgo(15) },
  { id: 'sla-002', contract_id: 'con-001', sla_name: 'Uptime Guarantee (99.9%)', target_response_time: '15 mins', target_resolution_time: '2 hours', status: 'at_risk', compliance_pct: 87.2, last_review_date: daysAgo(7) },
  { id: 'sla-003', contract_id: 'con-001', sla_name: 'Security Patch Management', target_response_time: '4 hours', target_resolution_time: '24 hours', status: 'active', compliance_pct: 95.0, last_review_date: daysAgo(30) },
  { id: 'sla-004', contract_id: 'con-002', sla_name: 'Core Banking Uptime SLA', target_response_time: '30 mins', target_resolution_time: '2 hours', status: 'breached', compliance_pct: 72.3, last_review_date: daysAgo(3) },
  { id: 'sla-005', contract_id: 'con-002', sla_name: 'Transaction Processing SLA', target_response_time: '1 hour', target_resolution_time: '8 hours', status: 'active', compliance_pct: 96.1, last_review_date: daysAgo(10) },
  { id: 'sla-006', contract_id: 'con-002', sla_name: 'Data Backup & Recovery', target_response_time: '4 hours', target_resolution_time: '24 hours', status: 'active', compliance_pct: 99.2, last_review_date: daysAgo(20) },
  { id: 'sla-007', contract_id: 'con-002', sla_name: 'Regulatory Compliance Reporting', target_response_time: '8 hours', target_resolution_time: '48 hours', status: 'at_risk', compliance_pct: 83.0, last_review_date: daysAgo(5) },
  { id: 'sla-008', contract_id: 'con-003', sla_name: 'Patient Data Management SLA', target_response_time: '1 hour', target_resolution_time: '4 hours', status: 'active', compliance_pct: 97.8, last_review_date: daysAgo(14) },
  { id: 'sla-009', contract_id: 'con-003', sla_name: 'Emergency Response SLA', target_response_time: '15 mins', target_resolution_time: '1 hour', status: 'active', compliance_pct: 99.5, last_review_date: daysAgo(7) },
  { id: 'sla-010', contract_id: 'con-004', sla_name: 'ERP Go-Live Support', target_response_time: '4 hours', target_resolution_time: '24 hours', status: 'active', compliance_pct: 91.4, last_review_date: daysAgo(21) },
  { id: 'sla-011', contract_id: 'con-004', sla_name: 'Training & Documentation SLA', target_response_time: '1 day', target_resolution_time: '5 days', status: 'active', compliance_pct: 100, last_review_date: daysAgo(45) },
  { id: 'sla-012', contract_id: 'con-005', sla_name: 'Platform Availability SLA', target_response_time: '2 hours', target_resolution_time: '8 hours', status: 'at_risk', compliance_pct: 88.6, last_review_date: daysAgo(6) },
  { id: 'sla-013', contract_id: 'con-005', sla_name: 'Order Processing SLA', target_response_time: '30 mins', target_resolution_time: '4 hours', status: 'active', compliance_pct: 94.3, last_review_date: daysAgo(15) },
  { id: 'sla-014', contract_id: 'con-006', sla_name: 'LMS Uptime SLA', target_response_time: '4 hours', target_resolution_time: '24 hours', status: 'active', compliance_pct: 99.1, last_review_date: daysAgo(30) },
  { id: 'sla-015', contract_id: 'con-007', sla_name: 'Clinical Data Security SLA', target_response_time: '1 hour', target_resolution_time: '6 hours', status: 'active', compliance_pct: 100, last_review_date: daysAgo(20) },
  { id: 'sla-016', contract_id: 'con-007', sla_name: 'Audit Trail Compliance', target_response_time: '2 hours', target_resolution_time: '12 hours', status: 'active', compliance_pct: 98.9, last_review_date: daysAgo(28) },
  { id: 'sla-017', contract_id: 'con-007', sla_name: 'Data Export & Reporting', target_response_time: '4 hours', target_resolution_time: '48 hours', status: 'active', compliance_pct: 96.5, last_review_date: daysAgo(35) },
  { id: 'sla-018', contract_id: 'con-008', sla_name: 'Tracking Accuracy SLA', target_response_time: '2 hours', target_resolution_time: '12 hours', status: 'active', compliance_pct: 93.8, last_review_date: daysAgo(10) },
  { id: 'sla-019', contract_id: 'con-008', sla_name: 'Delivery Notification SLA', target_response_time: '30 mins', target_resolution_time: '4 hours', status: 'at_risk', compliance_pct: 85.4, last_review_date: daysAgo(4) },
  { id: 'sla-020', contract_id: 'con-010', sla_name: 'Claims Processing SLA', target_response_time: '2 hours', target_resolution_time: '24 hours', status: 'active', compliance_pct: 97.2, last_review_date: daysAgo(12) },
  { id: 'sla-021', contract_id: 'con-010', sla_name: 'Policy Issuance SLA', target_response_time: '4 hours', target_resolution_time: '48 hours', status: 'active', compliance_pct: 99.0, last_review_date: daysAgo(25) },
  { id: 'sla-022', contract_id: 'con-010', sla_name: 'System Availability', target_response_time: '1 hour', target_resolution_time: '4 hours', status: 'active', compliance_pct: 98.5, last_review_date: daysAgo(18) },
  { id: 'sla-023', contract_id: 'con-011', sla_name: 'Solar Monitor Uptime', target_response_time: '8 hours', target_resolution_time: '72 hours', status: 'inactive', compliance_pct: 82.0, last_review_date: daysAgo(100) },
  { id: 'sla-024', contract_id: 'con-012', sla_name: 'Network Uptime SLA', target_response_time: '1 hour', target_resolution_time: '4 hours', status: 'breached', compliance_pct: 68.5, last_review_date: daysAgo(20) },
  { id: 'sla-025', contract_id: 'con-015', sla_name: 'Inventory Sync SLA', target_response_time: '2 hours', target_resolution_time: '12 hours', status: 'active', compliance_pct: 96.3, last_review_date: daysAgo(40) },
];

// ── Breach Incidents ─────────────────────────────────────────
export const MOCK_INCIDENTS = [
  { id: 'inc-001', incident_number: 'INC-0001', contract_id: 'con-002', incident_date: daysAgo(5), incident_type: 'Service Downtime', severity: 'critical', description: 'Core banking system went offline for 3 hours during peak business hours causing transaction failures.', root_cause: 'Database server disk failure on primary node.', resolution_status: 'in_progress', resolved_date: null, assigned_to_name: 'Admin User', company_name: 'FinEdge Capital Ltd', contract_number: 'CON-2024-0002', created_at: daysAgo(5) },
  { id: 'inc-002', incident_number: 'INC-0002', contract_id: 'con-001', incident_date: daysAgo(12), incident_type: 'SLA Breach', severity: 'high', description: 'Response time exceeded agreed 4-hour SLA for two consecutive critical tickets.', root_cause: 'Understaffing on weekend support team.', resolution_status: 'resolved', resolved_date: daysAgo(10), assigned_to_name: 'Priya Sharma', company_name: 'TechNova Solutions Pvt Ltd', contract_number: 'CON-2024-0001', created_at: daysAgo(12) },
  { id: 'inc-003', incident_number: 'INC-0003', contract_id: 'con-005', incident_date: daysAgo(8), incident_type: 'Deliverable Delay', severity: 'medium', description: 'Feature release delayed by 2 weeks due to third-party API integration issues.', root_cause: 'Payment gateway API changes were not communicated in advance.', resolution_status: 'resolved', resolved_date: daysAgo(3), assigned_to_name: 'Admin User', company_name: 'RetailMax India', contract_number: 'CON-2024-0005', created_at: daysAgo(8) },
  { id: 'inc-004', incident_number: 'INC-0004', contract_id: 'con-019', incident_date: daysAgo(3), incident_type: 'Service Downtime', severity: 'high', description: 'POS system failure at 12 retail outlets during sale event.', root_cause: 'Load balancer misconfiguration during maintenance window.', resolution_status: 'open', resolved_date: null, assigned_to_name: 'Priya Sharma', company_name: 'RetailMax India', contract_number: 'CON-2024-0016', created_at: daysAgo(3) },
  { id: 'inc-005', incident_number: 'INC-0005', contract_id: 'con-002', incident_date: daysAgo(18), incident_type: 'Data Security Breach', severity: 'critical', description: 'Unauthorized access attempt detected on banking API. Data integrity maintained but access logs show suspicious activity.', root_cause: 'Expired SSL certificate on API gateway.', resolution_status: 'closed', resolved_date: daysAgo(16), assigned_to_name: 'Admin User', company_name: 'FinEdge Capital Ltd', contract_number: 'CON-2024-0002', created_at: daysAgo(18) },
  { id: 'inc-006', incident_number: 'INC-0006', contract_id: 'con-003', incident_date: daysAgo(6), incident_type: 'Quality Issue', severity: 'medium', description: 'Billing module generating incorrect invoices for certain procedure codes.', root_cause: 'Incorrect tax rate configuration after GST update.', resolution_status: 'resolved', resolved_date: daysAgo(4), assigned_to_name: 'Priya Sharma', company_name: 'HealthFirst Hospitals', contract_number: 'CON-2024-0003', created_at: daysAgo(6) },
  { id: 'inc-007', incident_number: 'INC-0007', contract_id: 'con-012', incident_date: daysAgo(22), incident_type: 'Service Downtime', severity: 'critical', description: 'Nationwide telecom network outage affecting 50,000+ subscribers.', root_cause: 'Fiber cable cut during road construction near main exchange.', resolution_status: 'closed', resolved_date: daysAgo(20), assigned_to_name: 'Admin User', company_name: 'SpeedNet Telecom', contract_number: 'CON-2023-0002', created_at: daysAgo(22) },
  { id: 'inc-008', incident_number: 'INC-0008', contract_id: 'con-008', incident_date: daysAgo(9), incident_type: 'Deliverable Delay', severity: 'low', description: 'Monthly tracking accuracy report delayed by 2 days.', root_cause: 'Data aggregation script timeout on large dataset.', resolution_status: 'closed', resolved_date: daysAgo(7), assigned_to_name: 'Priya Sharma', company_name: 'LogiTrack Express', contract_number: 'CON-2024-0008', created_at: daysAgo(9) },
  { id: 'inc-009', incident_number: 'INC-0009', contract_id: 'con-016', incident_date: daysAgo(14), incident_type: 'Communication Gap', severity: 'medium', description: 'Client escalation on missed weekly status updates for 3 consecutive weeks.', root_cause: 'Automated email system failure; manual backup process not activated.', resolution_status: 'resolved', resolved_date: daysAgo(11), assigned_to_name: 'Admin User', company_name: 'AutoDrive Motors', contract_number: 'CON-2024-0013', created_at: daysAgo(14) },
  { id: 'inc-010', incident_number: 'INC-0010', contract_id: 'con-019', incident_date: daysAgo(25), incident_type: 'SLA Breach', severity: 'high', description: 'Resolution time exceeded SLA for 5 high-priority tickets over the month.', root_cause: 'High ticket volume during festive season without capacity planning.', resolution_status: 'closed', resolved_date: daysAgo(22), assigned_to_name: 'Priya Sharma', company_name: 'RetailMax India', contract_number: 'CON-2024-0016', created_at: daysAgo(25) },
];

// ── Alerts ───────────────────────────────────────────────────
export const MOCK_ALERTS = [
  { id: 'alt-001', contract_id: 'con-001', alert_type: 'renewal_critical', severity: 'critical', title: '⚠️ CRITICAL: Contract Renews in 5 Days', message: 'Contract "Annual IT Infrastructure Support Agreement" (CON-2024-0001) renewal date is in 5 days. Immediate action required.', is_read: false, is_dismissed: false, created_at: daysAgo(0) },
  { id: 'alt-002', contract_id: 'con-003', alert_type: 'renewal_critical', severity: 'critical', title: '⚠️ CRITICAL: Contract Renews in 3 Days', message: 'Contract "Hospital Management Software SLA" (CON-2024-0003) renewal date is in 3 days. Urgent action needed.', is_read: false, is_dismissed: false, created_at: daysAgo(0) },
  { id: 'alt-003', contract_id: 'con-002', alert_type: 'renewal_warning', severity: 'high', title: '📅 Renewal Reminder: 15 Days Left', message: 'Contract "Core Banking System Maintenance Contract" (CON-2024-0002) renewal is due in 15 days.', is_read: false, is_dismissed: false, created_at: daysAgo(0) },
  { id: 'alt-004', contract_id: 'con-005', alert_type: 'renewal_warning', severity: 'high', title: '📅 Renewal Reminder: 22 Days Left', message: 'Contract "E-Commerce Platform License Agreement" (CON-2024-0005) renewal is due in 22 days.', is_read: true, is_dismissed: false, created_at: daysAgo(0) },
  { id: 'alt-005', contract_id: 'con-004', alert_type: 'renewal_warning', severity: 'medium', title: '📅 Renewal Reminder: 28 Days Left', message: 'Contract "Manufacturing ERP Consulting Agreement" (CON-2024-0004) renewal is due in 28 days.', is_read: false, is_dismissed: false, created_at: daysAgo(0) },
  { id: 'alt-006', contract_id: 'con-002', alert_type: 'sla_breach', severity: 'critical', title: 'SLA Breach: Core Banking Uptime', message: 'SLA "Core Banking Uptime SLA" compliance dropped to 72.3%, well below the 90% threshold.', is_read: false, is_dismissed: false, created_at: daysAgo(0) },
  { id: 'alt-007', contract_id: 'con-012', alert_type: 'sla_breach', severity: 'critical', title: 'SLA Breach: Network Uptime SLA', message: 'SLA "Network Uptime SLA" compliance dropped to 68.5%. Immediate escalation required.', is_read: false, is_dismissed: false, created_at: daysAgo(0) },
  { id: 'alt-008', contract_id: 'con-001', alert_type: 'sla_at_risk', severity: 'high', title: 'SLA At Risk: Uptime Guarantee', message: 'SLA "Uptime Guarantee (99.9%)" compliance at 87.2%. Below 90% threshold for TechNova.', is_read: true, is_dismissed: false, created_at: daysAgo(0) },
  { id: 'alt-009', contract_id: 'con-005', alert_type: 'sla_at_risk', severity: 'high', title: 'SLA At Risk: Platform Availability', message: 'SLA "Platform Availability SLA" compliance at 88.6%. Monitor closely.', is_read: false, is_dismissed: false, created_at: daysAgo(0) },
  { id: 'alt-010', contract_id: 'con-011', alert_type: 'contract_expired', severity: 'critical', title: 'Contract Expired: Solar Energy Monitoring', message: 'Contract "Solar Energy Monitoring System" (CON-2023-0001) expired 35 days ago. Please review renewal status.', is_read: true, is_dismissed: false, created_at: daysAgo(0) },
  { id: 'alt-011', contract_id: 'con-012', alert_type: 'contract_expired', severity: 'critical', title: 'Contract Expired: Network Infrastructure SLA', message: 'Contract "Network Infrastructure SLA" (CON-2023-0002) expired 15 days ago.', is_read: false, is_dismissed: false, created_at: now.toISOString() },
  { id: 'alt-012', contract_id: 'con-002', alert_type: 'incident_created', severity: 'critical', title: 'New Breach Incident: Service Downtime', message: 'Critical incident INC-0001 logged for FinEdge Capital Ltd — Core banking system outage.', is_read: false, is_dismissed: false, created_at: now.toISOString() },
  { id: 'alt-013', contract_id: 'con-019', alert_type: 'incident_created', severity: 'high', title: 'New Breach Incident: Service Downtime', message: 'High severity incident INC-0004 logged for RetailMax India — POS system failure at 12 outlets.', is_read: true, is_dismissed: false, created_at: now.toISOString() },
];

// ── Dashboard Data ───────────────────────────────────────────
const today = new Date();

export const MOCK_DASHBOARD = {
  kpis: {
    contracts: { total: 20, active: 13, expired: 2, draft: 2, expiring_soon: 5, expiring_critical: 2, total_value: 38445000, active_value: 29600000 },
    customers: { total: 20, active: 17 },
    sla: { total: 25, avg_compliance: 92.4, at_risk: 5, breached: 2 },
    incidents: { total: 10, open: 2, critical_open: 1 },
    alerts: { total: 13, unread: 8, critical: 5 },
  },
  charts: {
    contractsByStatus: [
      { status: 'active', count: 13 }, { status: 'draft', count: 2 },
      { status: 'expired', count: 2 }, { status: 'renewed', count: 1 }, { status: 'archived', count: 0 },
    ],
    contractsByPriority: [
      { priority: 'critical', count: 2 }, { priority: 'high', count: 7 },
      { priority: 'medium', count: 8 }, { priority: 'low', count: 3 },
    ],
    monthlyTrends: Array.from({ length: 12 }, (_, i) => {
      const d = new Date(today); d.setMonth(d.getMonth() - 11 + i);
      return { month: d.toLocaleString('default', { month: 'short', year: '2-digit' }), month_date: d.toISOString(), new_contracts: 2 + Math.floor(Math.random() * 6), active: 8 + Math.floor(Math.random() * 6), total_value: 1000000 + Math.floor(Math.random() * 3000000) };
    }),
    slaComplianceTrend: Array.from({ length: 6 }, (_, i) => {
      const d = new Date(today); d.setMonth(d.getMonth() - 5 + i);
      return { month: d.toLocaleString('default', { month: 'short', year: '2-digit' }), month_date: d.toISOString(), avg_compliance: 88 + Math.random() * 10 };
    }),
  },
  upcomingRenewals: MOCK_CONTRACTS.filter(c => c.renewal_date && new Date(c.renewal_date) >= new Date() && new Date(c.renewal_date) <= new Date(Date.now() + 60 * 86400000) && c.status === 'active')
    .map(c => ({ ...c, days_left: Math.ceil((new Date(c.renewal_date) - new Date()) / 86400000) }))
    .sort((a, b) => a.days_left - b.days_left)
    .slice(0, 8),
  recentActivity: [
    { id: '1', action: 'created', entity_name: 'Cloud Migration Services Agreement', user_name: 'Priya Sharma', created_at: daysAgo(0) },
    { id: '2', action: 'updated', entity_name: 'Core Banking System Maintenance Contract', user_name: 'Admin User', created_at: daysAgo(1) },
    { id: '3', action: 'created', entity_name: 'INC-0001: Service Downtime - FinEdge Capital', user_name: 'Admin User', created_at: daysAgo(5) },
    { id: '4', action: 'archived', entity_name: 'Legacy Database Support Agreement', user_name: 'Admin User', created_at: daysAgo(6) },
    { id: '5', action: 'updated', entity_name: 'Hospital Management Software SLA', user_name: 'Priya Sharma', created_at: daysAgo(7) },
    { id: '6', action: 'created', entity_name: 'AI Analytics Platform License', user_name: 'Admin User', created_at: daysAgo(3) },
    { id: '7', action: 'exported', entity_name: 'Monthly SLA Compliance Report', user_name: 'Ravi Kumar', created_at: daysAgo(8) },
    { id: '8', action: 'updated', entity_name: 'Omnichannel Retail Platform Maintenance', user_name: 'Admin User', created_at: daysAgo(10) },
  ],
};
